compare result of evaluated xpath expression to value
Codeception/module-rest pull request #85
Opened 2022-08-09 16:48 UTC by pamoller

See https://github.com/Codeception/Codeception/issues/6546

Evaluate Xpath and compare their values. Youn can also use the xpath count function like checking id is unique:

````php
$this->module->seeResponseJsonXpathEvaluatesTo('count(//id) = 1', true);
````

2022-08-11 12:25 UTC, Naktibalda requested changes

2022-08-11 12:25 UTC, Naktibalda commented on src/Codeception/Module/REST.php
> +        $this->assertEquals(
Please use `assertSame` instead.

2022-08-11 12:25 UTC, Naktibalda commented on src/Codeception/Module/REST.php
> +        $this->assertNotEquals(
`assertNotSame`

2022-08-11 13:56 UTC, pamoller commented on src/Codeception/Module/REST.php
> +        $this->assertEquals(
Sure

2022-08-11 13:57 UTC, pamoller commented on src/Codeception/Module/REST.php
> +        $this->assertNotEquals(
sure

2022-08-13 11:27 UTC, Naktibalda commented
If count returns `1.0`, then it looks like a good idea to use `assertEquals`

2022-08-13 11:56 UTC, Naktibalda commented
In the module too.

2022-08-13 12:15 UTC, Naktibalda approved these changes

2022-08-13 12:16 UTC, merged

2022-08-13 12:19 UTC, Naktibalda commented
Released as 3.2.0 https://github.com/Codeception/module-rest/releases/tag/3.2.0